name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t caseyc24/answerbook-app:latest 

      - name: Push Docker image to Docker Hub
        run: |
          docker push caseyc24/answerbook-app:latest.

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@18.224.19.205 << 'EOF'
            # Pull the latest Docker image from Docker Hub
            docker pull caseyc24/answerbook-app:latest

            # Stop and remove the old container if it exists
            docker rm -f answerbook-container || true

            # Run the new container
            docker run -d -p 8080:8080 --name answerbook-container caseyc24/answerbook-app:latest
          EOF